name: auto doc
on:
  pull_request:
    branches: ["main"]

jobs:
  textlint:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - name: Setup node/npm
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          textlint_flags: "README*.md"
